Repository micronaut-projects/micronaut-aot, pull requests merged in 2021-12, with the labels that each got.

#23 Add more debug logging
  aot-api/build.gradle.kts
  aot-cli/build.gradle.kts
  aot-core/build.gradle.kts
  aot-core/src/main/java/io/micronaut/aot/core/config/SourceGeneratorLoader.java
  aot-core/src/main/java/io/micronaut/aot/core/context/DefaultSourceGenerationContext.java
  aot-std-optimizers/build.gradle.kts
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
  build-logic/src/main/groovy/io.micronaut.build.internal.aot-project.gradle
  settings.gradle.kts
Labels: type: improvement

#26 Fix conversion of booleans in Yaml
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/MapPropertySourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/MapPropertySourceGeneratorTest.groovy
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/YamlPropertySourceGeneratorTest.groovy
  aot-std-optimizers/src/test/resources/test-config.yml
Labels: type: bug

#28 Make sure that disabled configurations are honored
  aot-core/src/main/java/io/micronaut/aot/core/context/ApplicationContextAnalyzer.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy
Labels: type: bug

#29 Fix evaluation of `@Requires(configuration = ...)` conditions
  aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy
  aot-core/src/main/java/io/micronaut/aot/core/context/ApplicationContextAnalyzer.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy
Labels: type: bug

#34 Rename sealed environment -> cached environment
  aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/CachedEnvironmentSourceGenerator.java
  aot-std-optimizers/src/main/resources/META-INF/services/io.micronaut.aot.core.AOTCodeGenerator
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/CachedEnvironmentSourceGeneratorTest.groovy
Labels: type: improvement

#37 Add an option to configure the list of possible environments
  aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/DeduceEnvironmentSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/Environments.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/DeduceEnvironmentSourceGeneratorTest.groovy
Labels: type: improvement

#42 Make sure environment is available as a bean
  aot-core/src/main/java/io/micronaut/aot/core/context/ApplicationContextAnalyzer.java
Labels: type: bug

#44 Make sure that long literals are handled property
  aot-core/src/testFixtures/groovy/io/micronaut/aot/core/codegen/AbstractSourceGeneratorSpec.groovy
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/MapPropertySourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/MapPropertySourceGeneratorTest.groovy
Labels: type: bug

#46 Add an option to "force" a particular environment
  aot-api/src/main/java/io/micronaut/aot/MicronautAotOptimizer.java
  aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy
  aot-core/src/main/java/io/micronaut/aot/core/Configuration.java
  aot-core/src/main/java/io/micronaut/aot/core/Environments.java
  aot-core/src/main/java/io/micronaut/aot/core/config/DefaultConfiguration.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy
Labels: type: improvement

#48 Fix GraalVM feature generation
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/GraalVMOptimizationFeatureSourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/GraalVMOptimizationFeatureSourceGeneratorTest.groovy
Labels: type: bug

#47 [aot] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build
