Repository micronaut-projects/micronaut-aot, pull requests merged in 2022-01, with the labels that each got.

#52 Upgrade to Micronaut Build plugins 5.1.1
  settings.gradle.kts
Labels: type: dependency-upgrade

#54 Remove optimizer classpath
  aot-cli/src/main/java/io/micronaut/aot/cli/Main.java
  aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy
Labels: type: improvement

#57 Upgrade to build plugins 5.1.2
  settings.gradle.kts
Labels: relates-to: build, type: dependency-upgrade

#49 Upgrade for Micronaut 3.3
  aot-api/src/main/java/io/micronaut/aot/MicronautAotOptimizer.java
  aot-core/src/main/java/io/micronaut/aot/core/AOTContext.java
  aot-core/src/main/java/io/micronaut/aot/core/codegen/AbstractCodeGenerator.java
  aot-core/src/main/java/io/micronaut/aot/core/codegen/ApplicationContextConfigurerGenerator.java
  aot-core/src/main/java/io/micronaut/aot/core/codegen/DelegatingSourceGenerationContext.java
  aot-core/src/main/java/io/micronaut/aot/core/context/DefaultSourceGenerationContext.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/DeduceEnvironmentSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/EnvironmentPropertiesSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/KnownMissingTypesSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGenerator.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/PublishersSourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/EnvironmentPropertiesSourceGeneratorTest.groovy
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGeneratorTest.groovy
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/KnownMissingTypesSourceGeneratorTest.groovy
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGeneratorTest.groovy
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/PublishersSourceGeneratorTest.groovy
  gradle.properties
Labels: type: dependency-upgrade

#51 [aot] Update common files for branch master
  .github/workflows/graalvm.yml
Labels: relates-to: build

#58 Implement logback.xml to Java conversion
  aot-core/build.gradle.kts
  aot-std-optimizers/build.gradle.kts
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGeneratorTest.groovy
  aot-std-optimizers/src/test/resources/logback-test1.xml
  aot-std-optimizers/src/test/resources/logback-test2.xml
  aot-std-optimizers/src/test/resources/logback-test3.xml
  aot-std-optimizers/src/test/resources/logback-test4.xml
Labels: type: improvement

#63 Fix Joran classloading error if logback 1.3 isn't on classpath
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/Logback13GeneratorHelper.java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGenerator.java
Labels: type: bug

#61 Fix conversion of list and maps in Yaml
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/MapPropertySourceGenerator.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/YamlPropertySourceGeneratorTest.groovy
  aot-std-optimizers/src/test/resources/test-config.yml
Labels: type: bug

#64 ci: GraalVM github action from 21.3.0 to 22.0.0.2
  .github/workflows/graalvm.yml
  MAINTAINING.md
Labels: relates-to: build
