Repository micronaut-projects/micronaut-aot, pull requests merged in 2023-09, with the labels that each got.

#232 [aot] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#235 Fix duplicate logging when converting logback to Java
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/Logback14GeneratorHelper.java
  aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGeneratorTest.groovy
Labels: type: bug

#240 Remove ApplicationContextConfigurer from known service types
  aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
Labels: type: bug

#239 [aot] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#242 Improve documentation
  aot-core/src/main/java/io/micronaut/aot/core/Runtime.java
  aot-std-optimizers/build.gradle.kts
  aot-std-optimizers/src/configPropsGenerator/java/io/micronaut/aot/config/ConfigPropsGenerator.java
  src/main/docs/guide/introduction.adoc
  src/main/docs/guide/quickStart.adoc
Labels: type: docs
